### ISSUE TITLE
仓库demo跑不起来

### ISSUE THREAD

**Issue by 97Yates05** [umijs/qiankun#1152]
qiankun@2.3.3 examples:install C:\Users\ych\WebstormProjects\qiankun
> npm-run-all --serial build install:*

> qiankun@2.3.3 build C:\Users\ych\WebstormProjects\qiankun
> father-build

C:\Users\ych\WebstormProjects\qiankun\node_modules\@svgr\rollup\node_modules\@svgr\core\lib\config.js:32
const explorer = (0, _cosmiconfig.cosmiconfig)('svgr', {
                                              ^

TypeError: (0 , _cosmiconfig.cosmiconfig) is not a function
    at Object.<anonymous> (C:\Users\ych\WebstormProjects\qiankun\node_modules\@svgr\rollup\node_modules\@svgr\core\lib\config.js:32:47)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\ych\WebstormProjects\qiankun\node_modules\@svgr\rollup\node_modules\@svgr\core\lib\convert.js:8:15)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! qiankun@2.3.3 build: `father-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the qiankun@2.3.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ych\AppData\Roaming\npm-cache\_logs\2020-12-13T15_00_53_223Z-debug.log
ERROR: "build" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! qiankun@2.3.3 examples:install: `npm-run-all --serial build install:*`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the qiankun@2.3.3 examples:install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ych\AppData\Roaming\npm-cache\_logs\2020-12-13T15_00_53_260Z-debug.log

进程已结束,退出代码1

执行yarn examples:install时出现

**Comment by gongshun** [comment]
升级一下 `import-html-entry` 包应该就可以了，

**Comment by ramwin** [comment]
遇到了一样的问题.
```
"webpack@>=4.43.0 <6.0.0".
warning "dumi > @umijs/preset-dumi > dumi-theme-default@1.0.0-rc.4" has unmet peer dependency "react@^16.13.1".
warning "dumi > @umijs/preset-dumi > dumi-theme-default > prism-react-renderer@1.1.1" has unmet peer dependency "react@>=0.14.9".
warning "dumi > @umijs/preset-dumi > dumi-theme-default > rc-tabs@11.7.2" has unmet peer dependency "react@>=16.9.0".
warning "dumi > @umijs/preset-dumi > dumi-theme-default > rc-tabs@11.7.2" has unmet peer dependency "react-dom@>=16.9.0".
warning "dumi > @umijs/preset-dumi > dumi-theme-default > rc-tabs > rc-dropdown@3.2.0" has unmet peer dependency "react@*".
warning "dumi > @umijs/preset-dumi > dumi-theme-default > rc-tabs > rc-dropdown@3.2.0" has unmet peer dependency "react-dom@*".
warning "dumi > @umijs/preset-dumi > dumi-theme-default > rc-tabs > rc-menu@8.10.1" has unmet peer dependency "react@>=16.9.0".
warning "dumi > @umijs/preset-dumi > dumi-theme-default > rc-tabs > rc-menu@8.10.1" has unmet peer dependency "react-dom@>=16.9.0".
warning "dumi > @umijs/preset-dumi > dumi-theme-default > rc-tabs > rc-resize-observer@0.2.6" has unmet peer dependency "react@>=16.9.0".
warning "dumi > @umijs/preset-dumi > dumi-theme-default > rc-tabs > rc-resize-observer@0.2.6" has unmet peer dependency "react-dom@>=16.9.0".
warning "dumi > @umijs/preset-dumi > dumi-theme-default > rc-tabs > rc-util@5.5.1" has unmet peer dependency "react@>=16.9.0".
warning "dumi > @umijs/preset-dumi > dumi-theme-default > rc-tabs > rc-util@5.5.1" has unmet peer dependency "react-dom@>=16.9.0".
warning "dumi > @umijs/preset-dumi > dumi-theme-default > rc-tabs > rc-menu > mini-store@3.0.6" has unmet peer dependency "react@>=16.9.0".
warning "dumi > @umijs/preset-dumi > dumi-theme-default > rc-tabs > rc-menu > mini-store@3.0.6" has unmet peer dependency "react-dom@>=16.9.0".
warning "dumi > @umijs/preset-dumi > dumi-theme-default > rc-tabs > rc-menu > rc-motion@2.4.1" has unmet peer dependency "react@>=16.9.0".
warning "dumi > @umijs/preset-dumi > dumi-theme-default > rc-tabs > rc-menu > rc-motion@2.4.1" has unmet peer dependency "react-dom@>=16.9.0".
warning "dumi > @umijs/preset-dumi > dumi-theme-default > rc-tabs > rc-dropdown > rc-trigger > rc-align@4.0.9" has unmet peer dependency "react@>=16.9.0".
warning "dumi > @umijs/preset-dumi > dumi-theme-default > rc-tabs > rc-dropdown > rc-trigger > rc-align@4.0.9" has unmet peer dependency "react-dom@>=16.9.0".
warning "father-build > ts-loader@8.0.12" has unmet peer dependency "webpack@*".
warning " > ts-jest@25.5.1" has incorrect peer dependency "typescript@>=3.4 <4.0".
[4/4] Building fresh packages...
success Saved lockfile.
Done in 196.28s.

wangx@王祥的台式机:~/github/other/qiankun$ yarn examples:install
yarn run v1.22.10
$ npm-run-all --serial build install:*
$ father-build
/home/wangx/github/other/qiankun/node_modules/@svgr/rollup/node_modules/@svgr/core/lib/config.js:32
const explorer = (0, _cosmiconfig.cosmiconfig)('svgr', {
                                              ^

TypeError: (0 , _cosmiconfig.cosmiconfig) is not a function
    at Object.<anonymous> (/home/wangx/github/other/qiankun/node_modules/@svgr/rollup/node_modules/@svgr/core/lib/config.js:32:47)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/wangx/github/other/qiankun/node_modules/@svgr/rollup/node_modules/@svgr/core/lib/convert.js:8:15)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "build" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ramwin** [comment]
> 升级一下 `import-html-entry` 包应该就可以了，

升级了也不行. 
```
wangx@王祥的台式机:~/github/other/qiankun$ npm show import-html-entry

import-html-entry@1.11.0 | MIT | deps: 1 | versions: 78
import html and get the exports of entry
https://github.com/kuitos/import-html-entry#readme

keywords: html, importer

dist
.tarball: https://registry.npmjs.org/import-html-entry/-/import-html-entry-1.11.0.tgz
.shasum: 83626133bb6887cb2c3f7398ff12a47005f6ad7f
.integrity: sha512-GSnZ68e5ZF0unfRGH3MouN0pzz1y6VVviHyQ/95OSafMPoaLoO5w33BknRbFZ/n4C0hWNkN29Wg5ckLObQsmyA==
.unpackedSize: 62.8 kB

dependencies:
@babel/runtime: ^7.7.2

maintainers:
- kuitos <kuitos.lau@gmail.com>

dist-tags:
latest: 1.11.0  next: 1.6.0-2

published 2 weeks ago by kuitos <kuitos.lau@gmail.com>
wangx@王祥的台式机:~/github/other/qiankun$ yarn examples:install
yarn run v1.22.10
$ npm-run-all --serial build install:*
$ father-build
/home/wangx/github/other/qiankun/node_modules/@svgr/rollup/node_modules/@svgr/core/lib/config.js:32
const explorer = (0, _cosmiconfig.cosmiconfig)('svgr', {
                                              ^

TypeError: (0 , _cosmiconfig.cosmiconfig) is not a function
    at Object.<anonymous> (/home/wangx/github/other/qiankun/node_modules/@svgr/rollup/node_modules/@svgr/core/lib/config.js:32:47)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/wangx/github/other/qiankun/node_modules/@svgr/rollup/node_modules/@svgr/core/lib/convert.js:8:15)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "build" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
wangx@王祥的台式机:~/github/other/qiankun$

```

**Comment by gongshun** [comment]
第一步安装依赖有没有报错，需要用 `yarn install`，不能用 `npm install`

**Comment by ramwin** [comment]
> 第一步安装依赖有没有报错，需要用 `yarn install`，不能用 `npm install`

一开始用npm install的。运行错误后， 用了yarn install 没报错。 yarn example:install就报错了

**Comment by luocong2016** [comment]
rollup 版本有问题

**Comment by luocong2016** [comment]
重新删除no_modules 和 .lock 文件 重新安装基本可以

**Comment by 745984265** [comment]
我也遇到这个问题了，删除重新安装也不行，有解决吗？
