### ISSUE TITLE
子应用之间切换，报错Can't perform a React state update on an unmounted component...

### ISSUE THREAD

**Issue by hellojayjay** [umijs/qiankun#1477]
## What happens?

所有项目都是umi创建

子应用之间切换，报错：
Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    at SrcUmiPluginmodelHelpersExecutor (http://localhost:8001/umi.js:97114:20)
    at SrcUmiPluginmodelProvider (http://localhost:8001/umi.js:96754:23)

但是子应用都没有使用useEffect

## Mini Showcase Repository(REQUIRED)

https://github.com/hellojayjay/qiankun-issue

## How To Reproduce

1.来回点击【跳转app1】【跳转app2】
2.某次会报错
如下图
![error](https://user-images.githubusercontent.com/42774792/119992453-25fe8380-bffd-11eb-9c73-bba7f86623b2.gif)

**Expected behavior** 
不报错

## Context

- **qiankun Version**:
- qiankun "2.4.2"
- **Platform Version**:
- Windows 10 20H2
- **Browser Version**:
- Chrome  90.0.4430.212

**Comment by doubaozia** [comment]
同样的问题，而且来回切换几次就没有这个warning了。

**Comment by sogud** [comment]
同样遇到这个问题，在初次加载子应用就会报错。

**Comment by Issho-lin** [comment]
同样遇到这个问题，在初次加载子应用就会报错。+1

**Comment by johanazhu** [comment]
+2

**Comment by YeongaeLee** [comment]
同样的问题，子应用之间切换经常会报。

**Comment by gaona233** [comment]
解决了吗

**Comment by gaona233** [comment]
解决了吗

**Comment by SamYoY** [comment]
同样的问题，umi子应用与react子应用切换，有解决方案了吗？
