### ISSUE TITLE
运行install:examples时报错

### ISSUE THREAD

**Issue by wangzongxu** [umijs/qiankun#157]
## What happens?

当我把项目克隆岛本地，按照README运行
```bash
npm i
npm run install:examples
```
执行npm run install:examples时报错：

```
TypeScript: emit succeeded (with errors)
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: TypeScript: Compilation failed
    at Output.mightFinish (/Users/admin/Desktop/demo/qiankun/node_modules/gulp-typescript/release/output.js:130:43)
    at applySourceMap.then.appliedSourceMap (/Users/admin/Desktop/demo/qiankun/node_modules/gulp-typescript/release/output.js:65:22)
Emitted 'error' event at:
    at Duplexify._destroy (/Users/admin/Desktop/demo/qiankun/node_modules/duplexify/index.js:191:15)
    at /Users/admin/Desktop/demo/qiankun/node_modules/duplexify/index.js:182:10
    at process.internalTickCallback (internal/process/next_tick.js:70:11)
```

## Context

- **Platform**: mac
- **Browser Version**: *
- **Node Version**: 8.9.2 | 11.0.0

**Comment by zhoushan1** [comment]
+1

**Comment by CHU295** [comment]
+1

**Comment by kuitos** [comment]
间接依赖的 @types/vfile-message 包被 removed 导致的，resolved

**Comment by campcc** [comment]
try upgrading the node version ( node >= 16.0.0 ), this work for me
