### ISSUE TITLE
父应用vue 子应用react 加载子应用 父应用vue会崩溃

### ISSUE THREAD

**Issue by yitiaoxianyu0927** [umijs/qiankun#1717]
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:201:27)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}

**Comment by gongshun** [comment]
https://github.com/umijs/qiankun/issues/1428#issuecomment-862891643 或者 
https://github.com/umijs/qiankun/issues/1299#issuecomment-790468009
