### ISSUE TITLE
运行main项目的时候报错

### ISSUE THREAD

**Issue by klaaay** [umijs/qiankun#185]
## What happens?
`$ yarn start
yarn run v1.13.0
$ parcel index.html --port 7099
Server running at http://localhost:7099 
×  F:\qiankun\node_modules\import-html-entry\esm\index.js: Unknown version 10 of op_mob
    at Function.select (F:\qiankun\examples\main\node_modules\browserslist\index.js:1001:17)
    at F:\qiankun\examples\main\node_modules\browserslist\index.js:277:33
    at Array.reduce (<anonymous>)
    at resolve (F:\qiankun\examples\main\node_modules\browserslist\index.js:259:18)
    at browserslist (F:\qiankun\examples\main\node_modules\browserslist\index.js:383:21)
    at getTargets (F:\qiankun\examples\main\node_modules\@babel\preset-env\lib\targets-parser.js:179:48)
    at _default (F:\qiankun\examples\main\node_modules\@babel\preset-env\lib\index.js:225:46)
    at Object.default (F:\qiankun\examples\main\node_modules\@babel\helper-plugin-utils\lib\index.js:19:12)
    at getEnvPlugins (F:\qiankun\examples\main\node_modules\parcel-bundler\src\transforms\babel\env.js:62:34)
    at getEnvConfig (F:\qiankun\examples\main\node_modules\parcel-bundler\src\transforms\babel\env.js:21:28)`

## 相关环境信息
- **windows**：
- **v10.15.3**：

**Comment by hy-pillow** [comment]
![image](https://user-images.githubusercontent.com/6457155/70437224-110af900-1ac6-11ea-84b0-c7bb0e6df15e.png)
支持版本范围太大了吧，改成6的话还可以正常编译
应该是caniuse维护的的版本列表中无法找到opera mobile的10这个版本了

**Comment by kuitos** [comment]
@klaaay 楼上的方案能解决你的问题吗

**Comment by klaaay** [comment]
> @klaaay 楼上的方案能解决你的问题吗

这个是这个项目依赖的一个包这样是改import-html-entry包的package.json了，麻烦你能更新这个包嘛

**Comment by kuitos** [comment]
released
