### ISSUE TITLE
调用registerMicroApps报错：require is not defined

### ISSUE THREAD

**Issue by XiaoJ-96** [umijs/qiankun#1967]
```javascrpit
import { registerMicroApps, runAfterFirstMounted, setDefaultMountApp, start, initGlobalState } from "qiankun";

console.log(registerMicroApps);
```

报错详情：
```
index.bundle.js:2676 Uncaught ReferenceError: require is not defined
    at eval (concat.js?c04b:1:1)
    at Object.../../node_modules/.pnpm/registry.npmmirror.com+lodash@4.17.21/node_modules/lodash/concat.js (index.bundle.js:1519:1)
    at __webpack_require__ (index.bundle.js:2673:33)
    at fn (index.bundle.js:2906:21)
    at eval (loader.js:5:71)
    at Module.../../node_modules/.pnpm/registry.npmmirror.com+qiankun@2.6.3/node_modules/qiankun/es/loader.js (index.bundle.js:1698:1)
    at __webpack_require__ (index.bundle.js:2673:33)
    at fn (index.bundle.js:2906:21)
    at eval (apis.js:16:65)
    at Module.../../node_modules/.pnpm/registry.npmmirror.com+qiankun@2.6.3/node_modules/qiankun/es/apis.js (index.bundle.js:1643:1)

```

**Comment by ningminynwa** [comment]
朋友，解决了么？
