### ISSUE TITLE
运行yarn examples:install报错

### ISSUE THREAD

**Issue by huangjunchao** [umijs/qiankun#2106]
yarn install v1.22.19
[1/4] Resolving packages...
success Already up-to-date.
Done in 1.05s.
PS E:\code\qiankun\qiankun-master> yarn examples:install
yarn run v1.22.19
$ npm-run-all --serial build install:*
$ father-build
Clean dist directory
Build umd
×  error     Error: E:/code/qiankun/qiankun-master/src/loader.ts(133,33): semantic error TS2774: This condition will always return true since this function is always defined. Did 
you mean to call it instead? 
    at error (E:\code\qiankun\qiankun-master\node_modules\rollup\dist\shared\rollup.js:5253:30)
    at throwPluginError (E:\code\qiankun\qiankun-master\node_modules\rollup\dist\shared\rollup.js:17926:12)
    at Object.error (E:\code\qiankun\qiankun-master\node_modules\rollup\dist\shared\rollup.js:18533:24)
    at Object.error (E:\code\qiankun\qiankun-master\node_modules\rollup\dist\shared\rollup.js:18095:38)
    at E:\code\qiankun\qiankun-master\node_modules\rollup-plugin-typescript2\src\print-diagnostics.ts:41:11
    at arrayEach (E:\code\qiankun\qiankun-master\node_modules\rollup-plugin-typescript2\node_modules\lodash\lodash.js:516:11)
    at Function._.each [as forEach] (E:\code\qiankun\qiankun-master\node_modules\rollup-plugin-typescript2\node_modules\lodash\lodash.js:9368:14)
    at printDiagnostics (E:\code\qiankun\qiankun-master\node_modules\rollup-plugin-typescript2\src\print-diagnostics.ts:9:2)
    at Object.transform (E:\code\qiankun\qiankun-master\node_modules\rollup-plugin-typescript2\src\index.ts:244:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "build" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by jhunyiii** [comment]
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/53162654/170221717-8c06cbc9-f01c-47d3-ad07-2019e2e2d198.png">

**Comment by Volcanoboyboy** [comment]
![image](https://github.com/umijs/qiankun/assets/22393982/0d3f8f7b-545c-44b0-adf9-7b72aa391377)
