### ISSUE TITLE
主应用qiankun@2.7.2， 子应用qiankun@2.6.3，子应用存在动态加载的STYLE_TAG_NAME时，shadow dom隔离下，不能直接获取到元素报错

### ISSUE THREAD

**Issue by liangskyli** [umijs/qiankun#2137]
# 提问之前强烈建立您能先阅读一下[《如何正确的提出一个 Issue》](https://github.com/umijs/qiankun/issues/1115)

## 最小可复现仓库

为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN

## 复现步骤，错误日志以及相关配置
主应用qiankun@2.7.2， 子应用qiankun@2.6.3，
使用strictStyleIsolation隔离，主应用加载子应用报错
主应用qiankun@2.7.2， 子应用qiankun@2.6.3，子应用存在动态加载的STYLE_TAG_NAME时，shadow dom隔离下，不能直接获取到元素报错
```
[import-html-entry]: error occurs while executing normal script //cdn.bootcdn.net/ajax/libs/eruda/2.4.1/eruda.min.js
console.<computed> @ mf-dep____vendor.925ff15d.js:113872
console.<computed> @ devScripts.js:6523
（匿名） @ mf-dep____vendor.925ff15d.js:67281
setTimeout（异步）
throwNonBlockingError @ mf-dep____vendor.925ff15d.js:67280
exec @ mf-dep____vendor.925ff15d.js:67346
schedule @ mf-dep____vendor.925ff15d.js:67369
schedule @ mf-dep____vendor.925ff15d.js:67374
schedule @ mf-dep____vendor.925ff15d.js:67374
schedule @ mf-dep____vendor.925ff15d.js:67374
（匿名） @ mf-dep____vendor.925ff15d.js:67380
（匿名） @ mf-dep____vendor.925ff15d.js:67379
Promise.then（异步）
_execScripts @ mf-dep____vendor.925ff15d.js:67310
execScripts @ mf-dep____vendor.925ff15d.js:67443
_callee17$ @ mf-dep____vendor.925ff15d.js:77644
tryCatch @ mf-dep____vendor.925ff15d.js:77328
（匿名） @ mf-dep____vendor.925ff15d.js:77328
（匿名） @ mf-dep____vendor.925ff15d.js:77328
fulfilled @ mf-dep____vendor.925ff15d.js:15218
Promise.then（异步）
step @ mf-dep____vendor.925ff15d.js:15233
fulfilled @ mf-dep____vendor.925ff15d.js:15218
Promise.then（异步）
step @ mf-dep____vendor.925ff15d.js:15233
fulfilled @ mf-dep____vendor.925ff15d.js:15218
Promise.then（异步）
step @ mf-dep____vendor.925ff15d.js:15233
（匿名） @ mf-dep____vendor.925ff15d.js:15236
__awaiter @ mf-dep____vendor.925ff15d.js:15215
loadApp @ mf-dep____vendor.925ff15d.js:77553
_callee5$ @ mf-dep____vendor.925ff15d.js:76885
tryCatch @ mf-dep____vendor.925ff15d.js:76621
（匿名） @ mf-dep____vendor.925ff15d.js:76621
（匿名） @ mf-dep____vendor.925ff15d.js:76621
（匿名） @ mf-dep____vendor.925ff15d.js:15236
__awaiter @ mf-dep____vendor.925ff15d.js:15215
memorizedLoadingFn @ mf-dep____vendor.925ff15d.js:76824
W @ mf-dep____vendor.925ff15d.js:126043
C @ mf-dep____vendor.925ff15d.js:126043
loadMicroApp @ mf-dep____vendor.925ff15d.js:76919
（匿名） @ MicroApp.tsx:156
commitHookEffectListMount @ mf-dep____vendor.925ff15d.js:107062
commitPassiveMountOnFiber @ mf-dep____vendor.925ff15d.js:108829
commitPassiveMountEffects_complete @ mf-dep____vendor.925ff15d.js:108794
commitPassiveMountEffects_begin @ mf-dep____vendor.925ff15d.js:108781
commitPassiveMountEffects @ mf-dep____vendor.925ff15d.js:108769
flushPassiveEffectsImpl @ mf-dep____vendor.925ff15d.js:111003
flushPassiveEffects @ mf-dep____vendor.925ff15d.js:110948
（匿名） @ mf-dep____vendor.925ff15d.js:110738
workLoop @ mf-dep____vendor.925ff15d.js:125613
flushWork @ mf-dep____vendor.925ff15d.js:125586
performWorkUntilDeadline @ mf-dep____vendor.925ff15d.js:125880
queue.<computed> @ mf-dep____vendor.925ff15d.js:48148
run @ mf-dep____vendor.925ff15d.js:48122
listener @ mf-dep____vendor.925ff15d.js:48133
postMessage（异步）
post @ mf-dep____vendor.925ff15d.js:48138
setImmediate @ mf-dep____vendor.925ff15d.js:48150
schedulePerformWorkUntilDeadline @ mf-dep____vendor.925ff15d.js:125911
performWorkUntilDeadline @ mf-dep____vendor.925ff15d.js:125885
queue.<computed> @ mf-dep____vendor.925ff15d.js:48148
run @ mf-dep____vendor.925ff15d.js:48122
listener @ mf-dep____vendor.925ff15d.js:48133
postMessage（异步）
post @ mf-dep____vendor.925ff15d.js:48138
setImmediate @ mf-dep____vendor.925ff15d.js:48150
schedulePerformWorkUntilDeadline @ mf-dep____vendor.925ff15d.js:125911
requestHostCallback @ mf-dep____vendor.925ff15d.js:125935
unstable_scheduleCallback @ mf-dep____vendor.925ff15d.js:125788
scheduleCallback$1 @ mf-dep____vendor.925ff15d.js:111504
ensureRootIsScheduled @ mf-dep____vendor.925ff15d.js:109652
scheduleUpdateOnFiber @ mf-dep____vendor.925ff15d.js:109441
updateContainer @ mf-dep____vendor.925ff15d.js:112817
push../node_modules/react-dom/cjs/react-dom.development.js.ReactDOMHydrationRoot.render.ReactDOMRoot.render @ mf-dep____vendor.925ff15d.js:113229
renderClient @ mf-dep____vendor.925ff15d.js:16691
initialValue @ umi.ts:53
_callee2$ @ masterRuntimePlugin.tsx:104
tryCatch @ mf-dep____vendor.925ff15d.js:124645
invoke @ mf-dep____vendor.925ff15d.js:124876
（匿名） @ mf-dep____vendor.925ff15d.js:124701
asyncGeneratorStep @ mf-dep____vendor.925ff15d.js:10178
_next @ mf-dep____vendor.925ff15d.js:10200
Promise.then（异步）
asyncGeneratorStep @ mf-dep____vendor.925ff15d.js:10188
_next @ mf-dep____vendor.925ff15d.js:10200
（匿名） @ mf-dep____vendor.925ff15d.js:10207
（匿名） @ mf-dep____vendor.925ff15d.js:10196
_render @ masterRuntimePlugin.tsx:71
render @ masterRuntimePlugin.tsx:71
（匿名） @ mf-dep____vendor.925ff15d.js:126323
（匿名） @ mf-dep____vendor.925ff15d.js:126278
_callee$ @ umi.ts:30
tryCatch @ mf-dep____vendor.925ff15d.js:124645
invoke @ mf-dep____vendor.925ff15d.js:124876
（匿名） @ mf-dep____vendor.925ff15d.js:124701
asyncGeneratorStep @ mf-dep____vendor.925ff15d.js:10178
_next @ mf-dep____vendor.925ff15d.js:10200
Promise.then（异步）
asyncGeneratorStep @ mf-dep____vendor.925ff15d.js:10188
_next @ mf-dep____vendor.925ff15d.js:10200
Promise.then（异步）
asyncGeneratorStep @ mf-dep____vendor.925ff15d.js:10188
_next @ mf-dep____vendor.925ff15d.js:10200
（匿名） @ mf-dep____vendor.925ff15d.js:10207
（匿名） @ mf-dep____vendor.925ff15d.js:10196
_render @ umi.ts:16
render @ umi.ts:16
./.umi/umi.ts @ umi.ts:59
options.factory @ react refresh:6
__webpack_require__ @ bootstrap:24
fn @ hot module replacement:62
Promise.then（异步）
（匿名） @ umi.js:2
await in （匿名）（异步）
__webpack_require__.a @ async module:63
./mfsu-virtual-entry/umi.js @ RefreshUtils.js:271
options.factory @ react refresh:6
__webpack_require__ @ bootstrap:24
（匿名） @ startup:5
（匿名） @ startup:5
mf-dep____vendor.925ff15d.js:79085 Uncaught TypeError: Cannot read properties of undefined (reading 'contains')
    at HTMLHeadElement.appendChildOrInsertBefore [as appendChild] (mf-dep____vendor.925ff15d.js:79085:42)
    at O (//cdn.bootcdn.net/ajax/libs/eruda/2.4.1/eruda.min.js:1:447958)
    at Module.c (//cdn.bootcdn.net/ajax/libs/eruda/2.4.1/eruda.min.js:1:520788)
    at e (//cdn.bootcdn.net/ajax/libs/eruda/2.4.1/eruda.min.js:1:543812)
    at Object.c (//cdn.bootcdn.net/ajax/libs/eruda/2.4.1/eruda.min.js:1:298420)
    at e (//cdn.bootcdn.net/ajax/libs/eruda/2.4.1/eruda.min.js:1:543812)
    at eval (//cdn.bootcdn.net/ajax/libs/eruda/2.4.1/eruda.min.js:1:543715)
    at eval (//cdn.bootcdn.net/ajax/libs/eruda/2.4.1/eruda.min.js:1:277)
    at Proxy.eval (//cdn.bootcdn.net/ajax/libs/eruda/2.4.1/eruda.min.js:1:281)
    at window.__TEMP_EVAL_FUNC__ (//cdn.bootcdn.net/ajax/libs/eruda/2.4.1/eruda.min.js:3:23)
    at evalCode (mf-dep____vendor.925ff15d.js:67959:12)
    at geval (mf-dep____vendor.925ff15d.js:67314:55)
    at exec (mf-dep____vendor.925ff15d.js:67343:13)
    at schedule (mf-dep____vendor.925ff15d.js:67369:9)
    at schedule (mf-dep____vendor.925ff15d.js:67374:11)
    at schedule (mf-dep____vendor.925ff15d.js:67374:11)
    at schedule (mf-dep____vendor.925ff15d.js:67374:11)
    at mf-dep____vendor.925ff15d.js:67380:14
    at new Promise (<anonymous>)
    at mf-dep____vendor.925ff15d.js:67379:12
```
报错原因：
子应用存在动态加载的STYLE_TAG_NAME时，shadow dom隔离下，不能直接获取到元素
```
var getAppWrapperHeadElement = function getAppWrapperHeadElement(appWrapper) {
var rootElement = 'host' in appWrapper ? appWrapper.host : appWrapper;
// shadow dom隔离，这里不能直接获取到元素
return rootElement.getElementsByTagName(utils__WEBPACK_IMPORTED_MODULE_1_.qiankunHeadTagName)[0];
};

导致这里报错了
var mountDOM = target === 'head' ? getAppWrapperHeadElement(appWrapper) : appWrapper;
 dynamicStyleSheetElements.push(stylesheetElement);
// mountDOM为undefined 导致 错误：Uncaught TypeError: Cannot read properties of undefined (reading 'contains')
var referenceNode = mountDOM.contains(refChild) ? refChild : null;
return rawDOMAppendOrInsertBefore.call(mountDOM, stylesheetElement, referenceNode);



          
```

## 相关环境信息

- **qiankun 版本** 主应用qiankun@2.7.2 子应用qiankun@2.6.3
- **浏览器版本**：
- **操作系统**：

**Comment by liangskyli** [comment]
复现DEMO：https://github.com/liangskyli/umi4-qiankun-strictStyleIsolation-bug
