### ISSUE TITLE
子应用，在html中写js代码动态引入vue cdn报错，但是子应用单独访问时，可以运行

### ISSUE THREAD

**Issue by 1066826101** [umijs/qiankun#2394]
## 最小可复现仓库
https://github.com/1066826101/qiankun-demo

## 复现步骤，错误日志以及相关配置
 [import-html-entry]: error occurs while executing normal script http://localhost:8081/js/app.js
index.js?1f8c:146 Uncaught TypeError: Cannot read properties of undefined (reading '__esModule')
    at Object.exports.install (webpack-internal:///./node_modules/vue-hot-reload-api/dist/index.js:16:13)
    at eval (webpack-internal:///./src/App.vue:26:7)
    at Module../src/App.vue (:8081/js/app.js:29:1)
    at __webpack_require__ (:8081/js/app.js:228:33)
    at fn (:8081/js/app.js:461:21)
    at eval (webpack-internal:///./src/main.js:11:66)
    at Module../src/main.js (:8081/js/app.js:146:1)
    at __webpack_require__ (:8081/js/app.js:228:33)
    at eval (:8081/js/app.js:1349:109)
    at Function.__webpack_require__.O (:8081/js/app.js:274:23)
app-errors.js?17fe:11 Uncaught Error: application 'childApp' died in status LOADING_SOURCE_CODE: [qiankun]: You need to export lifecycle functions in childApp entry
    at getLifecyclesFromExports (webpack-internal:///./node_modules/qiankun/es/loader.js:208:9)
    at _callee17$ (webpack-internal:///./node_modules/qiankun/es/loader.js:356:35)
    at tryCatch (webpack-internal:///./node_modules/@babel/runtime/helpers/regeneratorRuntime.js:47:17)
    at Generator.eval (webpack-internal:///./node_modules/@babel/runtime/helpers/regeneratorRuntime.js:128:22)
    at Generator.eval [as next] (webpack-internal:///./node_modules/@babel/runtime/helpers/regeneratorRuntime.js:72:21)
    at asyncGeneratorStep (webpack-internal:///./node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:7:24)
    at _next (webpack-internal:///./node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:26:9)

## 相关环境信息
- **qiankun 版本**：2.9.2
- **浏览器版本**：chrome 97.0.4692.71（正式版本）（64 位）
- **操作系统**：window11

**Comment by gongshun** [comment]
的确存在这个bug：https://github.com/umijs/qiankun/issues/2362

但是你这样写，子应用单独运行应该也是有问题的，cdn的文件请求如果非常慢，后面的js文件执行就会报错

**Comment by 1066826101** [comment]
> 的确存在这个bug：#2362
> 
> 但是你这样写，子应用单独运行应该也是有问题的，cdn的文件请求如果非常慢，后面的js文件执行就会报错

这样写就是为了，在cdn很慢的情况下，我可以去访本地的vue.js。

**Comment by BadMooncc** [comment]
1、你这问题不属于人家框架的范畴，即便是你单独起一个项目这么写也会出问题，你可以多刷新几次看看 绝对有问题。
2、这个问题是script加载顺序的问题，你只要能确保你的js能在 vue.js加载成功之后执行就不会有问题，显然你这种写法没办法保证这个顺序
3、cdn加载慢你去访问本地资源，但是你的cdn资源还在加载 等于你加载了两个vue
