### ISSUE TITLE
官方demo 执行 yarn build , Maximum call stack size exceeded

### ISSUE THREAD

**Issue by longmajuxie** [umijs/qiankun#342]
官方demo 执行 yarn build ，出现下面错误
``
 λ yarn build
yarn run v1.22.4
$ father-build
Clean dist directory
Build cjs with babel
Clean lib directory
E:\study\qiankun-master\node_modules\mkdirp\index.js:91
                    throw err0;
                    ^

RangeError: Maximum call stack size exceeded
    at internal/fs/utils.js:424:38
    at hidden (internal/errors.js:241:14)
    at internal/fs/utils.js:438:3
    at hidden (internal/errors.js:241:14)
    at Object.mkdirSync (fs.js:756:10)
    at sync (E:\study\qiankun-master\node_modules\mkdirp\index.js:72:13)
    at sync (E:\study\qiankun-master\node_modules\mkdirp\index.js:78:24)
    at sync (E:\study\qiankun-master\node_modules\mkdirp\index.js:79:17)
    at sync (E:\study\qiankun-master\node_modules\mkdirp\index.js:79:17)
    at sync (E:\study\qiankun-master\node_modules\mkdirp\index.js:79:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
``
相关版本
λ node 
v13.11.  
λ yarn 
1.22.4 
λ npm -
6.9.0  
- **操作系统**：windows 10

**Comment by eynol** [comment]
看上去是fahter-build的问题，使用powershell 或者git 自带的bash执行试试呢？

**Comment by HerbertSHB** [comment]
![image](https://user-images.githubusercontent.com/28696661/77871129-bdd7d480-7275-11ea-8969-09a50bfad932.png)

这个是写错了把

**Comment by eynol** [comment]
> 这个是写错了把

这是1.x的修复，2.0不需要了

**Comment by HerbertSHB** [comment]
> > 这个是写错了把
> 
> 这是1.x的修复，2.0不需要了

我刚才拉master的时候，应该是代码没合进去23333333
