### ISSUE TITLE
生产构建文档

### ISSUE THREAD

**Issue by farzer** [umijs/qiankun#67]
## What happens?

没有找到相关生产构建部署的文档

**Comment by kuitos** [comment]
子应用部署可直接沿用以前的发布部署流程，没有什么要特殊处理的

**Comment by farzer** [comment]
请问可以把构建示例添加到example里面吗？

**Comment by kuitos** [comment]
构建示例具体指的是啥？

**Comment by farzer** [comment]
就example来说，目前的example要怎么构建生产环境的打包文件？

**Comment by kuitos** [comment]
webpack 就 webpack build, parcel 就 parcel build

**Comment by rqc-git** [comment]
想问问，您的 子应用项目 都做了哪些配置，除了暴露钩子函数~
我在做迁移遗留系统的项目，就在遗留项目中暴露了钩子，在example/main里面注册子应用程序，然后会出现许多问题~
1，react-dom.development.js:25215 GET http://localhost:3000/ 404 (Not Found)
2，react-dom.development.js:25215 Uncaught react app: Application 'react app' died in status UNMOUNTING: unmountComponentAtNode(...): Target container is not a DOM element.
    at eval (eval at exec (http://localhost:7099/main.e31bb0bc.js:31987:11), <anonymous>:30509:32)
    at Object.unmountComponentAtNode (eval at exec (http://localhost:7099/main.e31bb0bc.js:31987:11), <anonymous>:30512:11)
    at Array.unmount (eval at exec (http://localhost:7099/main.e31bb0bc.js:31987:11), <anonymous>:171157:21)
    at i (http://localhost:7099/main.e31bb0bc.js:32599:21)
    at http://localhost:7099/main.e31bb0bc.js:32601:38
3，react-dom.development.js:25215 Uncaught vue-hm-app: Application 'vue-hm-app' died in status LOADING_SOURCE_CODE: You need to export the functional lifecycles in vue-hm-app entry
    at _callee7$ (http://localhost:7099/main.e31bb0bc.js:33879:23)
    at tryCatch (http://localhost:7099/main.e31bb0bc.js:30657:40)
    at Generator.invoke [as _invoke] (http://localhost:7099/main.e31bb0bc.js:30883:22)
    at Generator.prototype.<computed> [as next] (http://localhost:7099/main.e31bb0bc.js:30709:21)
    at asyncGeneratorStep (http://localhost:7099/main.e31bb0bc.js:31553:24)
    at _next (http://localhost:7099/main.e31bb0bc.js:31575:9)
3，是我新注册的子应用程序
自己技术储备不够，读registerMicroApps（）方法源码，错误显示是我暴露的钩子不是函数，但自己找不到解决方案。
另外，希望@kuitos可以提供关于qiankun的详细文档，方便其构建与使用。

**Comment by kuitos** [comment]
@rqc-git 新开个 issue 并提供可复现的仓库

**Comment by bacy** [comment]
应该是钩子函数export但整个子项目都没有import，被线上摇树给干掉了，其他人没碰到这个问题吗
